fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

aymard:
    resource: "@AymardBundle/Controller/"
    type:     annotation

image_format:
    resource: "@AymardBundle/Resources/config/routing.yml"
