aymard_page:
    resource: "@AymardBundle/Controller/PageController.php"
    type:     annotation


avanzu_admin_logout:
    path: /logout
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

avanzu_admin_profile:
    path: /profile/{userid}/
    
aymard_bundle:
    resource: "@AymardBundle/Resources/config/routing.yml"
