liip_imagine: 
    resolvers:
       default:
            web_path: 
                web_root: %kernel.root_dir%/../web
                cache_prefix: media/cache
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/
    filter_sets:
        cache: ~
        photoThumb:
            quality: 75
            filters:
                thumbnail: { size: [300, 300], mode: inset }

