JMSTranslationBundle_ui:
  resource: "@JMSTranslationBundle/Controller/"
  type:     annotation
  prefix:   /admin/_trans

aymard_admin_page:
    resource: "@AymardBundle/Controller/PageController.php"
    type:     annotation

aymard_admin_image:
    resource: "@AymardBundle/Controller/ImageController.php"
    type:     annotation

aymard_default:
    resource: "@AymardBundle/Controller/DefaultController.php"
    type:     annotation


_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"