parameters:
  aymard.image_path: %kernel.root_dir%/../web/img/
  aymard.menu_listener.class: AymardBundle\EventListener\MenuItemListListener
  my_admin_bundle.show_user_listener.class: AymardBundle\EventListener\ShowUserListener
  
services:
  aymard.menu_listener: 
    class: "%aymard.menu_listener.class%"
    tags:
      - { event: theme.sidebar_setup_menu, method: onSetupMenu,  name: kernel.event_listener }

  my_admin_bundle.show_user_listener:
    class: %my_admin_bundle.show_user_listener.class%
    arguments: { container: "@security.token_storage" }
    tags:
      - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }